name       : haskell-stm-chans
version    : 3.0.0.4
release    : 4
source     :
    - http://hackage.haskell.org/package/stm-chans-3.0.0.4/stm-chans-3.0.0.4.tar.gz : 2344fc5bfa33d565bad7b009fc0e2c5a7a595060ba149c661f44419fc0d54738
license    : BSD-3-Clause
component  : programming.haskell
summary    : Additional types of channels for STM.
description: |
    Additional types of channels for STM.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
